### ISSUE TITLE
Only integer allowed

### ISSUE THREAD

**Issue by unleashed7** [Mx772/dragons-dogma-2-auto-character-creator#37]
The Creator does not allow integer as input, while the character creator (e.g. Chest Shape) does.

**Comment by Mx772** [comment]
Oooh, chest shape striking again. I'll get around to fixing this, in the mean time you can just edit the ini file it pops out in any text editor to add .5 if needed.

**Comment by unleashed7** [comment]
Tried doing that, but unfortunately the maker script also does not appreciate my floats 😄

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\mxrid\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
  File "main.py", line 285, in run_program
  File "main.py", line 303, in main
  File "main.py", line 37, in read_config
  File "main.py", line 38, in <dictcomp>
ValueError: invalid literal for int() with base 10: '30.5'
```

It's not a big issue really, to manually change one slider after it's done, just would be awesome if it could support floats too in the future.
